# -*- coding: utf-8 -*-
"""
@author: Bhavya/lovelornflamewizard

> Terminology:
    meat        <--  original message
    bacon       <--  encrypted message
    pepper      <--  encryption password
    salt        <--  randomness generated by hashing pepper
    grinder     <--  char ⇌ num, based on alphabet-ruleset

"""

GRINDER_CAPACITY = 95
salt_length = 8


def encrypt(meat, pepper, multiplier, print_mode):
    meat_length = len(meat)
    pepper_length = len(pepper)
    bacon = list(meat)
    
    for instance in range(0, multiplier+0, +1):
        pepper = pepper_shaker(pepper, instance)
        salt = salt_shaker(pepper, instance)
        
        for i in range(meat_length):
            a = char_grinder(bacon[i], 'CHAR')
            b = char_grinder(pepper[i%pepper_length], 'CHAR')
            c = char_grinder(salt[i%salt_length], 'CHAR')
            n = (a + (b*b) + (c*c*c) + i%pepper_length)%GRINDER_CAPACITY
            
            if(print_mode and instance == multiplier-1):
                print(char_grinder(n, "NUM"), end="")
            bacon[i] = char_grinder(n, 'NUM')
    
    if(not print_mode):
        return string(bacon)


def decrypt(bacon, pepper, multiplier, print_mode):
    bacon_length = len(bacon)
    pepper_length = len(pepper)
    meat = list(bacon)
    
    for instance in range(0, multiplier, +1):
        pepper = retrace_pepper(pepper, instance)
        salt = salt_shaker(pepper, instance)
    
    for instance in range(multiplier-1, -1, -1):
        for i in range(bacon_length):
            a = char_grinder(meat[i], 'CHAR')
            b = char_grinder(pepper[i%pepper_length], 'CHAR')
            c = char_grinder(salt[i%salt_length], 'CHAR')
            n = (a - (b*b) - (c*c*c) - i%pepper_length)%GRINDER_CAPACITY
            
            if(print_mode and instance == 0):
                print(char_grinder(n, "NUM"), end="")
            meat[i] = char_grinder(n,  'NUM')
        
        pepper = pepper_shaker(pepper, instance)
        salt = salt_shaker(pepper, instance)
    
    if(not print_mode):
        return string(meat)


def pepper_shaker(pepper, instance):
    pepper = list(pepper)
    pepper_length = len(pepper)
    
    if(instance == 1 or instance == 3):
        pepper = pepper[::-1]
    if(instance == 2):
        for i in range(pepper_length):
            if(i%2 == 0 and i != pepper_length-1):
                temp_particle = pepper[i];
                pepper[i] = pepper[i+1];
            if(i%2 == 1):
                pepper[i] = temp_particle;
    
    return string(pepper)


def retrace_pepper(pepper, instance):
    pepper = pepper_shaker(pepper, instance)
    return pepper


def salt_shaker(pepper, instance):
    A = 1; B = 0
    for c in pepper:
        A += char_grinder(c, 'CHAR')
        B += A
    
    return "{0:08d}".format(((A*B)**2)%99999999)


def char_grinder(package, package_type):
    alphabet = list(""" !"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~""")
    
    if(package_type == "CHAR"):
        return alphabet.index(package)
    if(package_type == "NUM"):
        return alphabet[package]


def string(list_):
    return "".join(list_)
